import Head from "next/head";
// import Link from "next/link";
// import { SignOutButton } from "@clerk/nextjs";
import { type NextPage } from "next";
import {
  createColumnHelper,
  flexRender,
  getCoreRowModel,
  useReactTable,
} from "@tanstack/react-table";
import { DateTime } from "luxon";

import { api } from "~/utils/api";

type Highlight = {
  highlight: string;
};

type Interaction = {
  title: string;
  location: string;
  date: Date;
  highlights: Highlight[];
};

type Contact = {
  name: string;
  affiliation: string;
  notes: string;
  position: string;
  company: string;
  interactions: Interaction[];
};

const defaultData: Contact[] = [
  {
    name: "Zach Canterbury",
    affiliation: "IMI",
    notes: "Ball State grad, interned with E&B in 2012",
    position: "Director of IN/OH Sales",
    company: "IMI",
    interactions: [
      {
        title: "Coffee at Patachou",
        location: "Patachou Coffee at Stutz",
        date: new Date(),
        highlights: [
          { highlight: "Early years in career are going to be a grind" },
          { highlight: "Still making cold calls in his new role" },
        ],
      },
      {
        title: "Intern Presentation",
        location: "IMI Corporate Office",
        date: new Date("2024-03-03"),
        highlights: [
          { highlight: "Gave feedback on customer scorecard project" },
          {
            highlight:
              "Interested in hiring me on if I wanted to switch to sales",
          },
        ],
      },
    ],
  },
];

const columnHelper = createColumnHelper<Contact>();

const columns = [
  columnHelper.accessor("name", {
    header: () => "Name",
    cell: (info) => info.getValue(),
    size: 120,
    maxSize: 150,
  }),
  columnHelper.accessor("affiliation", {
    header: () => "Affiliation",
    cell: (info) => info.renderValue(),
  }),
  columnHelper.accessor("position", {
    header: () => "Position",
    cell: (info) => info.renderValue(),
  }),
  columnHelper.accessor("company", {
    header: () => "Company",
    cell: (info) => info.renderValue(),
  }),
  columnHelper.accessor("notes", {
    header: "Notes",
    cell: (info) => {
      const val = info.getValue() as string;
      const maxLength = 35;
      const truncatedVal =
        val && val.length > maxLength
          ? val.substring(0, maxLength) + "..."
          : val;
      return truncatedVal;
    },
  }),
  columnHelper.accessor("interactions", {
    header: () => "Recent Activity",
    cell: (info) => {
      const interactions = info.getValue() as Interaction[];
      if (interactions.length === 0) {
        return ""; // Handle case when there are no interactions
      }

      const sorted = interactions.sort(
        (a, b) => b.date.getTime() - a.date.getTime(),
      );
      const recent = sorted[0];
      return recent?.title;
    },
  }),
  columnHelper.accessor("interactions", {
    header: () => "Activity Date",
    cell: (info) => {
      const interactions = info.getValue() as Interaction[];
      if (interactions.length === 0) {
        return ""; // Handle case when there are no interactions
      }

      const sorted = interactions.sort(
        (a, b) => b.date.getTime() - a.date.getTime(),
      );
      const recent = sorted[0];
      const convertedDate = DateTime.fromJSDate(
        recent?.date || new Date(),
      ).toFormat("MMMM dd, yyyy");
      return `${convertedDate}`;
    },
  }),
];

const Home: NextPage = () => {
  const { data } = api.contacts.getAll.useQuery();
  console.log(data);

  const table = useReactTable({
    data: defaultData,
    columns,
    getCoreRowModel: getCoreRowModel(),
  });

  return (
    <>
      <Head>
        <title>Network Buddy</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        {/* <SignOutButton /> */}
        <table className="w-11/12 bg-white">
          <thead className="">
            {table.getHeaderGroups().map((headerGroup) => (
              <tr key={headerGroup.id}>
                {headerGroup.headers.map((header) => (
                  <th key={header.id} className="border-2 bg-red-300 text-left">
                    {header.isPlaceholder
                      ? null
                      : flexRender(
                          header.column.columnDef.header,
                          header.getContext(),
                        )}
                  </th>
                ))}
              </tr>
            ))}
          </thead>
          <tbody>
            {table.getRowModel().rows.map((row) => (
              <tr key={row.id}>
                {row.getVisibleCells().map((cell) => (
                  <td key={cell.id} style={{ width: cell.column.getSize() }}>
                    {flexRender(cell.column.columnDef.cell, cell.getContext())}
                  </td>
                ))}
              </tr>
            ))}
          </tbody>
        </table>
      </main>
    </>
  );
};

export default Home;
