import Head from "next/head";
import { type ReactNode, useEffect, useState } from "react";
import {
  type IconDefinition,
  faUserPlus,
  faPowerOff,
  faXmark,
} from "@fortawesome/free-solid-svg-icons";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import {
  faBars,
  faCaretDown,
  faUserGroup,
} from "@fortawesome/free-solid-svg-icons";
import { Inter } from "next/font/google";
import { api } from "~/utils/api";
import { useSetContacts, useSetContactsLoading } from "~/store/AppStore";
import toast from "react-hot-toast";
import { useRouter } from "next/navigation";
import { SignOutButton } from "@clerk/nextjs";
import { useUser } from "@clerk/nextjs";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export default function Layout({ children }: { children: ReactNode }) {
  const [navOpen, setNavOpen] = useState<boolean>(false);
  const setContacts = useSetContacts();
  const setContactsLoading = useSetContactsLoading();
  const router = useRouter();
  const {
    data: contacts,
    isLoading: contactsLoading,
    error: contactsError,
  } = api.contacts.getAll.useQuery();

  useEffect(() => {
    if (contacts) {
      setContacts(contacts);
    }
    setContactsLoading(contactsLoading);
  }, [contacts, setContacts, contactsLoading]);

  if (contactsError)
    toast.error("Error retrieving contacts, please try again later!");

  const session = useUser();
  const username = session.user?.fullName;

  const NavIcon = (props: {
    icon: IconDefinition;
    openOnClick?: boolean;
    title: string;
    link?: string;
    isLogout?: boolean;
  }) => {
    const button = () => {
      const handleButtonClick = () => {
        if (props.openOnClick) {
          setNavOpen(!navOpen);
        } else if (props.link) {
          router.push(props.link);
          setNavOpen(false);
        }
      };
      return (
        <div
          className={`flex h-14 items-center overflow-x-hidden text-[#8099a7] transition ease-in-out ${props.isLogout ? "hover:bg-red-200 hover:text-red-500" : "hover:bg-site-purple-l hover:text-site-purple-r"}
        ${navOpen ? "w-56" : "w-14"} ${props.openOnClick ? "rounded-tl-xl" : ""}
        `}
          onClick={handleButtonClick}
        >
          <div className="absolute flex h-14 w-14 items-center justify-center">
            <FontAwesomeIcon
              icon={props.icon}
              style={{ height: "20px", width: "20px" }}
            />
          </div>
          {navOpen && <p className="pl-14">{props.title}</p>}
        </div>
      );
    };

    if (!props.isLogout) {
      return button();
    } else return <SignOutButton>{button()}</SignOutButton>;
  };

  return (
    <>
      <Head>
        <title>Network Buddy</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        className={`flex h-screen flex-col items-center justify-center bg-gradient-to-bl from-site-blue-r to-site-purple-r font-sans lg:p-5 ${inter.variable}`}
      >
        <div className="flex h-full w-full flex-row bg-white lg:rounded-lg">
          {/* start desktop nav */}
          <div
            className={` hidden flex-col transition-all delay-100 ease-in-out lg:flex ${navOpen ? "w-56" : "w-14"}`}
          >
            <NavIcon icon={faBars} openOnClick={true} title="Settings" />
            <NavIcon icon={faUserGroup} title="Contacts" link="/contacts" />
            <NavIcon
              icon={faUserPlus}
              title="Add Contact"
              link="/contact/new"
            />
            <NavIcon icon={faPowerOff} title="Logout" isLogout={true} />
          </div>
          {/* end desktop nav */}
          <div className="relative flex w-full flex-col">
            <div className="z-30 flex min-h-14 w-full items-center bg-white px-6 text-[#8099a7] lg:rounded-lg">
              <div className="flex w-1/6 items-center"></div>
              <div
                className="pointer flex w-2/3 cursor-pointer justify-center hover:text-site-purple-r"
                onClick={() => router.push("/")}
              >
                <p className="bg-gradient-to-bl from-site-blue-r to-site-purple-r bg-clip-text text-xl font-semibold text-transparent xs:text-3xl">
                  NETWORK BUDDY
                </p>
              </div>
              <div className="flex w-1/6 items-center justify-end">
                <p className="hidden lg:block">{username}</p>
                <div className="lg:hidden" onClick={() => setNavOpen(!navOpen)}>
                  <FontAwesomeIcon
                    icon={navOpen ? faXmark : faBars}
                    style={{ height: "20px", width: "20px" }}
                  />
                </div>
              </div>
            </div>
            <div
              className={`${navOpen ? "flex lg:hidden" : "hidden"} absolute z-50 mt-14 w-full flex-col items-center justify-center bg-white transition-all delay-100 ease-in-out`}
            >
              <NavIcon icon={faUserGroup} title="Contacts" link="/contacts" />
              <NavIcon
                icon={faUserPlus}
                title="Add Contact"
                link="/contact/new"
              />
              <NavIcon icon={faPowerOff} title="Logout" isLogout={true} />
            </div>
            <div className="flex h-full flex-col overflow-scroll rounded-br-lg bg-gray-100 md:p-6 lg:overflow-hidden">
              {navOpen ? (
                <div className="fixed inset-0 z-20 bg-black opacity-50 lg:hidden"></div>
              ) : null}

              {children}
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
